TRUSTED_DOMAINS = [
    'youtube.com', 'facebook.com', 'twitter.com', 'instagram.com', 'whatsapp.com',
    'linkedin.com', 'snapchat.com', 'tiktok.com', 'telegram.org', 'zoom.us',
    'slack.com', 'discord.com', 'google.com', 'microsoft.com', 'apple.com',
    'adobe.com', 'cloudflare.com', 'mozilla.org', 'github.com', 'stackoverflow.com',
    'wordpress.com', 'dropbox.com', 'canva.com', 'amazon.com', 'flipkart.com',
    'ebay.com', 'aliexpress.com', 'walmart.com', 'bestbuy.com', 'target.com',
    'shopify.com', 'bbc.com', 'cnn.com', 'nytimes.com', 'theguardian.com',
    'reuters.com', 'forbes.com', 'netflix.com', 'spotify.com', 'hulu.com',
    'disneyplus.com', 'primevideo.com', 'hotstar.com', 'twitch.tv', 'imdb.com',
    'wikipedia.org', 'coursera.org', 'edx.org', 'khanacademy.org', 'udemy.com',
    'udacity.com', 'codeacademy.com', 'paypal.com', 'stripe.com', 'coinbase.com',
    'binance.com', 'bankofamerica.com', 'chase.com', 'gmail.com', 'yahoo.com',
    'outlook.com', 'protonmail.com', 'iiitsurat.ac.in', 'mit.edu', 'harvard.edu',
    'stanford.edu', 'iitb.ac.in', 'iitd.ac.in', 'iitk.ac.in', 'iitkgp.ac.in',
    'iitm.ac.in', 'iitroorkee.ac.in', 'iitgn.ac.in', 'iitbhilai.ac.in', 'iitj.ac.in',
    'iitbbs.ac.in', 'iiti.ac.in', 'iitism.ac.in', 'nits.ac.in', 'nitrkl.ac.in',
    'nitsikkim.ac.in', 'nitw.ac.in', 'nitc.ac.in', 'nitt.edu', 'uber.com',
    'nith.ac.in', 'nitk.ac.in', 'nitj.ac.in', 'nitrr.ac.in', 'nitsri.ac.in',
    'nitmanipur.ac.in', 'svnit.ac.in',
]
